#+OPTIONS: ^:nil num:nil p:nil timestamp:nil todo:nil date:nil creator:nil author:nil toc:nil
#+TITLE: Иголка в стоге сессий, или Байт-код регулярных выражений
* DONE Аннотация

  Семнадцать миллиардов событий, шестьдесят миллионов пользовательских сессий и невесть сколько
  виртуальных свиданий происходят в Badoo ежедневно. Каждое из событий аккуратно сохраняется в
  реляционные базы данных для последующего анализа на SQL и не только на нем. Современные
  распределенные тразакционные базы данных с их десятками терабайт данных - настоящее чудо
  современной инженерной мысли.

  Но SQL как воплощение реляционной алгебры в своих стандартных реализациях не позволяет
  формулировать запросы в терминах упорядоченных последовательностей кортежей.

  В последней из статей, посвященных виртуальным машинам, я расскажу про альтернативный подход:
  движок регулярных выражений ("Поросячий Матчер"), определенных на пользовательских сессиях.

* TODO Предыстория и задача



* TODO Сравниваем по бумажке
* TODO Подпоследовательности событий
* TODO Раздвоение личности, или Ветвления в последовательностях
* TODO Регулярные выражения на событиях
* TODO Заключение
