#+OPTIONS: ^:nil num:nil p:nil timestamp:nil todo:nil date:nil creator:nil author:nil toc:nil
#+TITLE: Иголка в стоге сессий, или Байт-код регулярных выражений
* DONE Аннотация

  Семнадцать миллиардов событий, шестьдесят миллионов пользовательских сессий и невесть сколько
  виртуальных свиданий происходят в Badoo ежедневно. Каждое из событий аккуратно сохраняется в
  реляционные базы данных для последующего анализа на SQL и не только на нем.

  Современные распределенные транзакционные базы данных с десятками терабайт данных - настоящее чудо
  инженерной мысли. Но SQL как воплощение реляционной алгебры в стандартных реализациях не позволяет
  формулировать сложные запросы в терминах упорядоченных последовательностей кортежей.

  В последней из моих статей, посвященных виртуальным машинам, я расскажу про альтернативный подход:
  движок регулярных выражений ("Поросячий Матчер"), определенных для последовательностей событий -
  пользовательских сессий.

* DONE О событиях и сессиях

  Мы хотим находить сессии по запросами вида: "посчитать все сессии, где имеется указанная
  подпоследовательность событий", или "найти части сессии, описанные заданным шаблоном", или
  "вернуть ту часть сессии, которая случилась после заданного шаблона", или "посчитать, сколько
  сессий достигли определенных частей шаблона". Это может пригодиться для самых разнообразных
  практических анализов: поиск подозрительных сессий, вороночный анализ и т.д.

  Искомые подпоследовательности надо как-то описывать. В самой простой форме эта задача похожа на
  обычный поиск подстроки в тексте; нам же хочется иметь инструмент помощнее - регулярные выражения.
  А современные реализации движков регулярных выражений чаще всего используют - вы угадали! -
  виртуальные машины.

  Созданием небольших виртуальных машинок для сопоставления сессий с регулярными выражениями мы и
  займемся. Но давайте сначала уточним определения.

  Итак, /событие/ состоит из типа события, времени, контекста и набора атрибутов, специфичных для
  каждого из типов.

  /Тип/ и /контекст/ каждого из событий это целые числа из предопределенных списков. Если с типами
  событий все понятно, то контекст это, например, номер экрана, на котором произошло заданное
  событие.

  /Атрибут/ события это произвольное целое число, смысл которого определяется типом события. Атрибутов
  у события может не быть, или быть несколько.

  /Сессия/ это последовательность событий, отсортированных по времени.

  Но давайте, наконец, перейдем к делу. "Гул затих. я вышел на подмостки. "

* TODO Сравниваем по бумажке
* TODO Я, еще раз я и я
* TODO Множественные личности и ветвления в шаблонах
* TODO Регулярные выражения на событиях
* TODO Заключение
